### ISSUE TITLE
Como aprender o básico de Python?

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional-trilhas-estudos#3]

**Comment by endersonmenezes** [comment]
Autor: <preencher>
Link do Curso: <preencher>
-----
Seção 1: Apresentação
Seção 2: Preparando o ambiente
Seção 3: Introdução à linguagem Python
Seção 4: Variáveis e Tipos de Dados em Python
Seção 5: Estruturas Lógicas e Condicionais em Python
Seção 6: Estruturas de Repetição em Python
Seção 7: Coleções Python
Seção 8: Funções em Python
Seção 9: Comprehensions em Python
Seção 10: Expressões Lambdas e Funções Integradas
Seção 11: Debugando e Tratando erros
Seção 12: Trabalhando com Módulos Python
Seção 13: Leitura e Escrita em Arquivos
Seção 14: Iteradores e Geradores Python
Seção 15: Decoradores em Python
Seção 16: Orientação a Objetos com Python
Seção 17: Herança e Polimorfismo
Seção 18: Manipulando Arquivos CSV e JSON
Seção 19: Trabalhando com Data e Hora em Python
Seção 20: Testes com Python
Seção 21: Encerramento
Seção 22: Gerenciamento de Memória em Python
Seção 23: Checagem de Tipos em Python
Seção 24: Novidades do Python 3.8
Seção 25: Projeto Python 1 - Game
Seção 26: Projeto Python 2 - Mercado
Seção 27: Projeto Python 3 - Banco
----

**Comment by endersonmenezes** [comment]
https://www.cursoemvideo.com/course/python-3-mundo-1/

**Comment by endersonmenezes** [comment]
https://www.cursoemvideo.com/course/python-3-mundo-2/

**Comment by endersonmenezes** [comment]
https://www.cursoemvideo.com/course/python-3-mundo-3/

**Comment by endersonmenezes** [comment]
Seção 1: Apresentação
https://www.codingame.com/playgrounds/34774/introducao-a-programacao-python---prof--marco-vaz/apresentacao
https://wiki.python.org.br/PythonApresentacao
https://www.slideshare.net/MayogaX/apresentando-a-linguagem-de-programao-python

**Comment by melissarr** [comment]
**Aprendendo o básico de Python** 

Seção 1: Apresentação
- https://www.codingame.com/playgrounds/34774/introducao-a-programacao-python---prof--marco-vaz/apresentacao
- https://wiki.python.org.br/PythonApresentacao
- https://www.slideshare.net/MayogaX/apresentando-a-linguagem-de-programao-python

Seção 2: Preparando o ambiente
- https://developer.mozilla.org/pt-BR/docs/Learn/Server-side/Django/development_environment
- https://digitalinnovation.one/artigos/guia-de-passo-a-passo-de-como-preparar-o-ambiente-python-utilizando-django
- https://medium.com/welcome-to-the-django/guia-definitivo-para-organizar-meu-ambiente-python-a16e2479b753

Seção 3: Introdução à linguagem Python
- https://python.org.br/introducao/
- https://www.devmedia.com.br/meetup-introducao-ao-python/40245

Seção 4: Variáveis e Tipos de Dados em Python
- https://algoritmosempython.com.br/cursos/programacao-python/tipos-basicos/
- https://cadernoscicomp.com.br/tutorial/introducao-a-programacao-em-python-3/python-variaveis-operadores-e-tipos-de-dados/
- https://panda.ime.usp.br/cc110/static/cc110/03-variaveis.html

Seção 5: Estruturas Lógicas e Condicionais em Python
- https://www.hashtagtreinamentos.com/estruturas-condicionais-no-python
- https://pense-python.caravela.club/05-condicionais-e-recursividade/03-operadores-logicos.html

Seção 6: Estruturas de Repetição em Python
- https://www.devmedia.com.br/estruturas-de-repeticao-em-python/41551
- https://www.treinaweb.com.br/blog/estruturas-condicionais-e-de-repeticao-no-python
- https://www.hashtagtreinamentos.com/estruturas-de-repeticao-python

Seção 7: Coleções Python
- https://www.devmedia.com.br/colecoes-no-python-listas-tuplas-e-dicionarios/40678
- https://www.phylos.net/2021-03-08/python-sequencias-e-colecoes/

Seção 8: Funções em Python
- https://algoritmosempython.com.br/cursos/programacao-python/funcoes/
- https://panda.ime.usp.br/pensepy/static/pensepy/05-Funcoes/funcoes.html
- https://www.dcc.ufrj.br/~fabiom/mab225/07func.pdf

Seção 9: Comprehensions em Python
- https://pythonacademy.com.br/blog/list-comprehensions-no-python
- https://pythonhelp.wordpress.com/2011/03/01/list-comprehension/

Seção 10: Expressões Lambdas e Funções Integradas
- https://www.codingame.com/playgrounds/52499/programacao-python-intermediario---prof--marco-vaz/funcao-lambda
- https://www.hashtagtreinamentos.com/funcoes-lambda-python
- https://pythonhelp.wordpress.com/tag/lambda/

Seção 11: Debugando e Tratando erros
- https://panda.ime.usp.br/panda/static/pensepy/Appendices/app_a.html
- https://pythonhelp.wordpress.com/2012/12/31/deu-erro-e-agora-o-que-eu-faco/
- https://cadernoscicomp.com.br/tutorial/introducao-a-programacao-em-python-3/tratamento-de-erros-e-excecoes/

Seção 12: Trabalhando com Módulos Python
- https://www.pythonprogressivo.net/2018/07/import-Como-Criar-Importar-Usar-Modulo-Python-Curso.html
- https://cadernoscicomp.com.br/tutorial/introducao-a-programacao-em-python-3/modulos/
- https://docs.python.org/pt-br/3/tutorial/modules.html

Seção 13: Leitura e Escrita em Arquivos
- https://panda.ime.usp.br/pensepy/static/pensepy/10-Arquivos/files.html
- https://academiahopper.com.br/trabalhando-com-arquivos-em-python/
- 

Seção 14: Iteradores e Geradores Python
- https://pythonacademy.com.br/blog/iterators-e-generators-em-python
- https://ichi.pro/pt/iteradores-iteraveis-e-geradores-132206850510725
- https://qastack.com.br/programming/2776829/difference-between-pythons-generators-and-iterators

Seção 15: Decoradores em Python
- https://pythoniluminado.netlify.app/decoradores
- https://wiki.python.org.br/Decoradores_Python_(Python_Decorators)
- https://pt.stackoverflow.com/questions/23628/como-funcionam-decoradores-em-python

Seção 16: Orientação a Objetos com Python
- https://panda.ime.usp.br/pensepy/static/pensepy/13-Classes/classesintro.html
- https://www.devmedia.com.br/python-orientado-a-objetos-com-o-framework-cherrypy/33489
- https://wiki.python.org.br/ProgramacaoOrientadaObjetoPython

Seção 17: Herança e Polimorfismo
- https://www.pythonprogressivo.net/2018/11/Polimorfismo-O-que-Como-Usar-Como-fazer.html
- https://medium.com/code-rocket-blog/entendendo-o-super-do-python-da17ee8d26ca
- https://www.devmedia.com.br/conceitos-e-exemplos-polimorfismo-programacao-orientada-a-objetos/18701

Seção 18: Manipulando Arquivos CSV e JSON
- https://imasters.com.br/back-end/data-science-importando-dados-com-python

Seção 19: Trabalhando com Data e Hora em Python
- https://vaiprogramar.com/como-trabalhar-com-data-hora-python-datetime/
- https://docs.python.org/pt-br/3/library/datetime.html
- https://pythonhelp.wordpress.com/2012/07/10/trabalhando-com-datas-e-horas-em-python-datetime/

Seção 20: Testes com Python
- https://dev.to/womakerscode/testes-em-python-parte-1-introducao-43ei

Seção 21: Encerramento
- https://qastack.com.br/programming/73663/how-to-terminate-a-python-script
- https://www.ti-enxame.com/pt/python/como-pararterminar-um-script-python-de-execucao/1043433651/

Seção 22: Gerenciamento de Memória em Python
- https://www.agatetepe.com.br/gerenciamento-de-memoria-python/
- https://weekly-geekly-es.imtqy.com/articles/pt441568/index.html

Seção 23: Checagem de Tipos em Python
- https://www.horadecodar.com.br/2021/03/30/como-checar-o-tipo-de-uma-variavel-em-python-3/
- https://medium.com/gutierri/checagem-de-tipos-no-python-1533fe1e786f

Seção 24: Novidades do Python 3.8
- https://docs.python.org/pt-br/dev/whatsnew/3.8.html
- https://medium.com/python-weekly-brazil/python-3-8-o-que-vem-por-ai-22f4a1ed954e

Seção 25: Projeto Python 1 - Game
- https://www.codigofluente.com.br/aula-01-criando-games-em-python/
- https://pythonacademy.com.br/blog/como-criar-jogos-com-python-e-kivy
- https://www.pythonprogressivo.net/2018/10/Como-Criar-Jogo-Velha-Python.html

Seção 26: Projeto Python 2 - Mercado
- 

Seção 27: Projeto Python 3 - Banco
-
